syntax = "proto3";

option csharp_namespace = "ReportService";

service GrpcReports {
    rpc GetAuctionReport (GetAuctionReportRequest) returns (GrpcAuctionReportResponse);
    rpc GetBidReport (GetBidReportRequest) returns (GrpcBidReportResponse);    
    rpc GetNotificationReport (GetNotificationReportRequest) returns (GrpcNotificationReportResponse);
    rpc GetDiagramData (GetDiagramReportRequest) returns (GetDiagramReportResponse);
    rpc GetCommunicationReport (GetCommunicationReportRequest) returns (GrpcCommunicationReportResponse);
}

message GetAuctionReportRequest {
    string AuctionReportRequest = 1;
}

message GetBidReportRequest {
    string BidReportRequest = 1;
}

message GetNotificationReportRequest {
    string NotificationReportRequest = 1;
}

message GetDiagramReportRequest {
    string DiagramReportRequest = 1;
}

message GrpcAuctionReportResponse {
    string auctionRezult = 1;
}

message GrpcBidReportResponse {
    string bidRezult = 1;
}

message GrpcNotificationReportResponse {
    string notificationRezult = 1;
}

message GetDiagramReportResponse {
    string diagramRezult = 1;
}

message GetCommunicationReportRequest {
    string CommunicationReportRequest = 1;
}

message GrpcCommunicationReportResponse {
    string communicationRezult = 1;
}