syntax = "proto3";

option csharp_namespace = "ReportService";

service GrpcReports {
    rpc GetAuctionReport (GetAuctionReportRequest) returns (GrpcAuctionReportResponse);
    rpc GetDiagramData (GetDiagramReportRequest) returns (GetDiagramReportResponse);    
}

message GetAuctionReportRequest {
    string AuctionReportRequest = 1;
}

message GrpcAuctionReportResponse {
    string auctionRezult = 1;
}

message GetDiagramReportRequest {
    string DiagramReportRequest = 1;
}

message GetDiagramReportResponse {
    string diagramRezult = 1;
}
