// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SearchService.Data;

#nullable disable

namespace SearchService.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    [Migration("20240316105357_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SearchService.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("AuctionEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AuctionEnd");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreateAt");

                    b.Property<int>("CurrentHighBid")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentHighBid");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Make")
                        .HasColumnType("text")
                        .HasColumnName("Make");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("Mileage");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("Model");

                    b.Property<int>("ReservePrice")
                        .HasColumnType("integer")
                        .HasColumnName("ReservePrice");

                    b.Property<string>("Seller")
                        .HasColumnType("text")
                        .HasColumnName("Seller");

                    b.Property<int>("SoldAmount")
                        .HasColumnType("integer")
                        .HasColumnName("SoldAmount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Winner")
                        .HasColumnType("text")
                        .HasColumnName("Winner");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("Year");

                    b.HasKey("Id")
                        .HasName("PK_Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("PK_Items");

                    b.ToTable("Items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
