// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20240403045158_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Entities.NotifyUser", b =>
                {
                    b.Property<string>("UserLogin")
                        .HasColumnType("text")
                        .HasColumnName("UserLogin");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("AuctionId");

                    b.HasKey("UserLogin", "AuctionId")
                        .HasName("PK_NotifyUserId");

                    b.HasIndex("AuctionId", "UserLogin")
                        .IsUnique()
                        .HasDatabaseName("IX_NotifyUser_AuctionId_UserLogin");

                    b.ToTable("NotifyUser", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
