<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NuspecFile>Utils.nuspec</NuspecFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AuctionContracts" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />  
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="VaultSharp" Version="1.17.5.1" />
    <PackageReference Include="MassTransit.Kafka" Version="8.3.4" />  
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logging/" />
  </ItemGroup>

</Project>
