<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NuspecFile>Utils.nuspec</NuspecFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AuctionContracts" Version="1.0.1" />   
    <PackageReference Include="VaultSharp" Version="1.17.5.1" />
    <PackageReference Include="MassTransit.Kafka" Version="8.5.7" />  
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logging/" />
     <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
